### ISSUE TITLE
Add a new function that renew automatically the free domain on no-ip.com periodically

### ISSUE THREAD

**Issue by bphd** [jonasof/cpanel-dns-updater#5]

**Comment by jonasof** [comment]
Hello @bphd, can you describe a little more what is your need? no-ip.com support is out of scope of this project. Maybe those projects can do what you need:

https://github.com/loblab/noip-renew
https://hugoks3.github.io/plugin-noip/en_US/

**Comment by bphd** [comment]
It was implemented? Nice, gimme the commit link

**Comment by bphd** [comment]
Welp

**Comment by jonasof** [comment]
Please check if these apps do what you need:

To auto renew free domains in no-ip.com:

- https://github.com/loblab/noip-renew
- https://github.com/tomitomas/plugin-noip

To update the domain IP in no-ip.com:

- https://www.noip.com/pt-BR/integrate/request
